# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [4]:
import numpy as np

In [5]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [10]:
arr_zeroes = np.zeros((3, 3))
arr_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [11]:
evenely_spaced= np.linspace(0, 5, 10)
evenely_spaced

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [12]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [13]:
random_matrix= np.random.rand(4, 4)
random_matrix

array([[0.1601824 , 0.52100473, 0.23331618, 0.27183607],
       [0.0553785 , 0.50489674, 0.55601836, 0.33873435],
       [0.3602    , 0.50289794, 0.53800414, 0.50480506],
       [0.43810468, 0.05527204, 0.4595939 , 0.68325598]])


---

### Exercise 6:
Find the shape of a NumPy array.


In [14]:
shape = random_matrix.shape
shape

(4, 4)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [15]:
reshape = np.arange(16).reshape(4, 4)
reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [16]:
dataype = random_matrix.dtype
dataype

dtype('float64')


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [17]:
even_numbers = np.arange(1, 101)
even_nbrs = even_numbers[even_numbers % 2 == 0]
even_nbrs

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [18]:
random_int = np.random.randint(10, 51, (6, 6))
random_int

array([[12, 14, 46, 32, 36, 34],
       [48, 19, 17, 27, 17, 24],
       [38, 35, 29, 42, 13, 14],
       [38, 23, 46, 48, 21, 25],
       [43, 25, 33, 13, 39, 27],
       [29, 28, 22, 47, 25, 10]])


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [20]:
submatrix_extraction = random_int[1:4, 2:5]
submatrix_extraction

array([[17, 27, 17],
       [29, 42, 13],
       [46, 48, 21]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [21]:
array_sum = random_int.sum()
array_sum

np.int64(1039)


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [25]:
mean_arr = evenely_spaced.mean()
median_arr = np.median(evenely_spaced)
std_arr = evenely_spaced.std()
std_arr

np.float64(1.5957118462605635)


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [26]:
max_arr = even_nbrs.max()
min_arr = even_nbrs.min()
print(max_arr, min_arr)

100 2



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [27]:
arr_random = np.random.randint(0, 100, 20)
max_index = np.argmax(arr_random)
max_index

np.int64(0)


---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [28]:
arr_reverse = np.arange(10)[::-1]
arr_reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [30]:
element_arr = np.random.randint(0, 15, (3, 3))
element_arr1= np.random.randint(0, 15, (3, 3))
wise_product = element_arr * element_arr1
wise_product

array([[ 4, 77, 39],
       [18, 44, 25],
       [42, 14,  4]])


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [31]:
diagonal_arr = np.array([1, 2, 3])
diagonal_arr = np.diag(diagonal_arr)
diagonal_arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [32]:
arr_mult1 = np.array([[1, 2], [3, 4]])
arr_mult2= np.array([[5, 6], [7, 8]])
dot_mult = np.dot(arr_mult1, arr_mult2)
dot_mult

array([[19, 22],
       [43, 50]])


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [33]:
flatten_arr = arr_mult1.flatten()
flatten_arr

array([1, 2, 3, 4])


---

### Exercise 21:
Stack two NumPy arrays vertically.


In [34]:
vertical_arr1 = np.array([[1, 2], [3, 4]])
vertical_arr2 = np.array([[5, 6]])
stack_arr = np.vstack((vertical_arr1, vertical_arr2))
stack_arr

array([[1, 2],
       [3, 4],
       [5, 6]])


---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [38]:
horizontally_arr = np.hstack((vertical_arr1, vertical_arr2.T))
horizontally_arr

array([[1, 2, 5],
       [3, 4, 6]])


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [39]:
sub_array= np.arange(12)
split_arr = np.split(sub_array, 4)
split_arr

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [40]:
round_arr = np.random.rand(5, 5)
rounded_arr = np.round(round_arr, 2)
rounded_arr

array([[0.9 , 0.8 , 0.04, 0.3 , 0.  ],
       [0.93, 0.43, 0.56, 0.32, 0.16],
       [0.4 , 0.9 , 0.49, 0.3 , 0.26],
       [0.83, 0.81, 0.36, 0.69, 0.62],
       [0.1 , 0.74, 0.53, 0.73, 0.85]])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [41]:
arr_unique = np.array([1, 2, 3, 2, 1, 4])
unique_el= np.unique(arr_unique)
unique_el

array([1, 2, 3, 4])


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [42]:
replace_arr = np.array([1, 5, 3, 0, 8])
replace_arr[replace_arr < 3] = 3
replace_arr

array([3, 5, 3, 3, 8])


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [43]:
arr_cumul = np.array([1, 2, 3])
cumul_sum= np.cumsum(arr_cumul)
cumul_sum

array([1, 3, 6])


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [45]:
arr_nonzero = np.array([0, 1, 0, 2, 3])
nonzeroes = np.count_nonzero(arr_nonzero)
nonzeroes

3


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [46]:
sort_arr = np.random.randint(0, 100, 10)
sort_arr = np.sort(sort_arr)
sort_arr

array([11, 39, 65, 69, 72, 73, 74, 76, 90, 94])


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [47]:
wise_arr= np.random.randint(1, 10, (3, 3))
row_sum= wise_arr.sum(axis=1)
col_sum = wise_arr.sum(axis=0)
print(row_sum, col_sum)

[12 24  8] [16 13 15]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [48]:
arr_normal = np.random.rand(3, 3)
normalize= (arr_normal - arr_normal.min()) / (arr_normal.max() - arr_normal.min())
normalize

array([[0.        , 0.70026444, 0.54544977],
       [0.71747723, 0.96350148, 0.75727254],
       [0.83530061, 1.        , 0.49277282]])


---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [49]:
arr_product1 = np.array([1, 2])
arr_product2 = np.array([3, 4])
dot_product= np.dot(arr_product1, arr_product2)
dot_product

np.int64(11)


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [51]:
square_matrix = np.array([[1, 2], [3, 4]])
trace_matrix = np.trace(square_matrix)
trace_matrix

np.int64(5)


---

### Exercise 34:
Create a 2D array and swap two rows.


In [ ]:
mat34 = np.array([[1, 2], [3, 4]])
mat34[[0, 1]] = mat34[[1, 0]]
mat34


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [53]:
arr_convert = np.array([1, 2, 3])
col_vec = arr_convert[:, np.newaxis]
col_vec

array([[1],
       [2],
       [3]])


---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [54]:
determinant_arr = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
determinant_matrix = np.linalg.det(determinant_arr)
determinant_matrix

np.float64(0.9999999999999964)


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [55]:
eigen_arr = np.array([[4, -2], [1, 1]])
eigvalues, eigvectors = np.linalg.eig(eigen_arr)
print(eigvalues, eigvectors)

[3. 2.] [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [56]:
#Solve: 10x + 5y = 15, 2x + 5y = 30
linear_arr1= np.array([[10, 5], [2, 5]])
linear_arr2= np.array([15, 30])
sol_arr = np.linalg.solve(linear_arr1, linear_arr2)
sol_arr

array([-1.875,  6.75 ])


---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [57]:
arr_gaussian = np.array([1, 2, 3])
gaussian_matrix = np.random.normal(0, 1, arr_gaussian.shape)
noise_gaussian = arr_gaussian + gaussian_matrix
noise_gaussian

array([-0.02163246,  0.79650607,  2.27123745])


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [58]:
arr_element4 = np.random.randint(20, 30, (4, 4))
diagonal_matrix = np.diag(arr_element4)
diagonal_matrix

array([23, 27, 24, 20])


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [59]:
random_values = np.random.rand(100) * 100
clip_matrix = np.clip(random_values, 10, 50)
clip_matrix

array([16.36993053, 50.        , 50.        , 35.20248006, 16.92399248,
       50.        , 50.        , 18.94839945, 10.        , 10.        ,
       50.        , 16.90352793, 45.86379908, 50.        , 50.        ,
       50.        , 10.        , 42.18818879, 49.30732719, 47.52729685,
       43.55797322, 10.        , 32.29114534, 47.88944659, 26.0377171 ,
       50.        , 50.        , 23.0784016 , 50.        , 25.85451177,
       21.36133557, 50.        , 50.        , 10.        , 50.        ,
       10.        , 50.        , 50.        , 50.        , 14.28550189,
       50.        , 45.75851313, 50.        , 50.        , 50.        ,
       20.52097392, 50.        , 11.16985861, 27.04809237, 50.        ,
       50.        , 47.94048678, 50.        , 50.        , 41.69626743,
       28.51905905, 50.        , 50.        , 50.        , 10.        ,
       50.        , 34.01623534, 32.40679444, 50.        , 50.        ,
       13.078032  , 50.        , 16.14515647, 50.        , 50.  


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [61]:
replace_negatives = np.array([[-3, 2], [5, -5]])
replace_negatives[replace_negatives < 0] = 0
replace_negatives

array([[0, 2],
       [5, 0]])


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [62]:
arr_product3 = np.array([1, 2])
arr_product4 = np.array([3, 4])
inner_arr = np.inner(arr_product3, arr_product4)
outer_arr = np.outer(arr_product3, arr_product4)
print(inner_arr, outer_arr)

11 [[3 4]
 [6 8]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [63]:
pair_wise = np.random.rand(4, 2)
from scipy.spatial.distance import pdist, squareform
distances_arr = squareform(pdist(pair_wise))
distances_arr

array([[0.        , 0.36739891, 0.29933529, 0.33632998],
       [0.36739891, 0.        , 0.2752355 , 0.27362878],
       [0.29933529, 0.2752355 , 0.        , 0.46147561],
       [0.33632998, 0.27362878, 0.46147561, 0.        ]])


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [64]:
arr_dict = np.array([('John', 35, 1.7), ('Doe', 30, 1.8)],
                 dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
arr_dict

array([('John', 35, 1.7), ('Doe', 30, 1.8)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f4')])


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [65]:
count_unique= np.random.randint(0, 5, (5, 5))
unique_values, count_arr = np.unique(count_unique, return_counts=True)
count_arr

array([3, 5, 6, 5, 6])


---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [66]:
substract_arr = np.random.rand(3, 3)
mean_arr47 = substract_arr.mean(axis=1, keepdims=True)
centered_arr = substract_arr - mean_arr47
centered_arr

array([[-0.21739931,  0.21276624,  0.00463308],
       [-0.24635462,  0.22641933,  0.01993528],
       [ 0.07964359, -0.23931819,  0.1596746 ]])


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [ ]:
arr48 = np.random.randint(0, 100, 10)
any_gt_50 = np.any(arr48 > 50)
any_gt_50


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [67]:
arr49 = np.random.rand(10)
window = 3
moving_avg49 = np.convolve(arr49, np.ones(window)/window, mode='valid')
moving_avg49

array([0.38663402, 0.47623783, 0.51294872, 0.55754582, 0.2563978 ,
       0.13369459, 0.35685877, 0.60275262])


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [68]:
x50 = np.random.rand(10)
y50 = np.random.rand(10)
corr50 = np.corrcoef(x50, y50)[0, 1]
corr50

np.float64(0.5523889778275566)


---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [69]:
rad51 = np.array([0, np.pi/2, np.pi])
deg51 = np.degrees(rad51)
deg51

array([  0.,  90., 180.])


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [93]:
std_var = np.random.rand(10)
var_arr = np.var(std_var)
std_arr = np.std(std_var)
print(var_arr, std_arr)

0.12822021312317616 0.35807850134178143



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [92]:
max_values = np.random.rand(3, 3)
max_index53 = np.argmax(max_values, axis=1)
max_index53_col = np.argmax(max_values, axis=0)
print(max_index, max_index53_col)

0 [2 2 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [91]:
inverse_matrix = np.array([[4, 7], [2, 6]])
inverse_matrix1 = np.linalg.inv(inverse_matrix)
inverse_matrix1

array([[ 0.6, -0.7],
       [-0.2,  0.4]])


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [90]:
random_values55 = np.random.rand(10)
standardized_arr = (random_values55 - np.mean(random_values55)) / np.std(random_values55)
standardized_arr

array([-0.35286621,  1.35078119,  0.54074925, -1.13817567, -0.01523574,
       -0.761404  ,  0.02746631, -0.52613488,  2.05339668, -1.17857694])


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [89]:
sub_matrix = np.array([1, 2, 3])
sub_matrix2 = np.array([4, 5, 6])
added_arr = sub_matrix + sub_matrix2
sub_solution = sub_matrix - sub_matrix2
print(added_arr, sub_solution)

[5 7 9] [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [88]:
random_arr57 = np.random.rand(15)
max_index57 = np.argmax(random_arr57)
max_index57

np.int64(7)


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [87]:
rotate_arr = np.arange(9).reshape(3, 3)
rotated_arr = np.rot90(rotate_arr)
rotated_arr

array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [86]:
norm_arr = np.array([[1, 2], [3, 4]])
frobenius_arr = np.linalg.norm(norm_arr)
frobenius_arr

np.float64(5.477225575051661)


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [85]:
slice_arr = np.arange(27).reshape(3, 3, 3)
sub_arr = slice_arr[1:, :, 1:]
sub_arr

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])


---